### ISSUE TITLE
Error in FSE

### ISSUE THREAD

**Issue by bystrzan** [wpspices/responsive-controls#6]
`TypeError: Cannot read properties of undefined (reading '__experimentalGetPreviewDeviceType')` while on site-editor just after activation "use responsive options".
It's on all default themes and all past 3 versions of WordPress.

I believe this could solve the problem: https://github.com/WordPress/gutenberg/issues/39248

**Comment by wpspices** [comment]
Issue resolved via [PR](https://github.com/wpspices/responsive-controls/pull/8)

**Comment by bystrzan** [comment]
I'll tst it, BUT wondering why I missed it as I research and read ALL of ALL GH repos and didn't find it (ealier stuff). It's drive me crazy. I have nothing right now, but still have some $ even $1 - can you make an account for $ in revolut or something so I can? BTC would be - even small donations - better than, but my company thinks about Your project/ plugin as a bigger thing to invest. My mail wpspices@bystrzan.pl - shoot me an email please.
